<template>
  <div>
    <v-row>
      <v-col cols="12">
        <FilterArea :data_filter="data_area" :search="search" />
      </v-col>
    </v-row>
  </div>
</template>

<script>
import FilterArea from "./FilterArea.vue";

export default {
  components: {
    FilterArea,
  },
  data() {
    return {
      search: "",
      data_area: [
        {
          idrole: "10666",
          namerole: "โรงพยาบาลมหาราชนครราชสีมา",
          area: "เขต 1",
          province: "นครราชสีมา",
          district: "เมืองนครราชสีมา",
          sub_district: "ด่านขุนทด",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 2",
          province: "หนองบัวลำภู",
          district: "เมืองหนองบัวลำภู",
          sub_district: "ในเมือง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลมหาราชนครราชสีมา",
          area: "เขต 1",
          province: "บุรีรัมย์",
          district: "เมืองบุรีรัมย์",
          sub_district: "ชุมเมือง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 3",
          province: "สระแก้ว",
          district: "เมืองสระแก้ว",
          sub_district: "โพธิ์ชัย",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 3",
          province: "ชัยภูมิ",
          district: "เมืองชัยภูมิ",
          sub_district: "บ้านเล่า",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 2",
          province: "อุดรธาณี",
          district: "เมืองอุดรธาณี",
          sub_district: "หมากแข้ง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 4",
          province: "เชียงใหม่",
          district: "เมืองเชียงใหม่",
          sub_district: "ช้างเผือก",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 4",
          province: "แม่ฮ่องสอน",
          district: "เมืองแม่ฮ่องสอน",
          sub_district: "จองคำ",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 5",
          province: "ลำพูน",
          district: "เมืองลำพูน",
          sub_district: "เวียงยอง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 5",
          province: "ลำปาง",
          district: "เมืองลำปาง",
          sub_district: "หัวเวียง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 6",
          province: "น่าน",
          district: "ภูเพียง",
          sub_district: "น้ำแก่น",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 6",
          province: "แพร่",
          district: "เมืองแพร่",
          sub_district: "เวียงชัย",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },

        {
          idrole: "10666",
          namerole: "โรงพยาบาลมหาราชนครราชสีมา",
          area: "เขต 1",
          province: "นครราชสีมา",
          district: "เมืองนครราชสีมา",
          sub_district: "บ้านใหม่",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 2",
          province: "หนองบัวลำภู",
          district: "เมืองหนองบัวลำภู",
          sub_district: "ท่าหลวง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลมหาราชนครราชสีมา",
          area: "เขต 1",
          province: "บุรีรัมย์",
          district: "เมืองบุรีรัมย์",
          sub_district: "ชุมเมือง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 3",
          province: "สระแก้ว",
          district: "เมืองสระแก้ว",
          sub_district: "บ้านค้อ",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 3",
          province: "ชัยภูมิ",
          district: "เมืองชัยภูมิ",
          sub_district: "โนนสมบูรณ์",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 2",
          province: "อุดรธาณี",
          district: "เมืองอุดรธาณี",
          sub_district: "ดงดวน",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 4",
          province: "เชียงใหม่",
          district: "เมืองเชียงใหม่",
          sub_district: "สุเทพ",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 4",
          province: "แม่ฮ่องสอน",
          district: "เมืองแม่ฮ่องสอน",
          sub_district: "ทุ่งช้าง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 5",
          province: "ลำพูน",
          district: "เมืองลำพูน",
          sub_district: "นาแก",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 5",
          province: "ลำปาง",
          district: "เมืองลำปาง",
          sub_district: "ป่าซาง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 6",
          province: "น่าน",
          district: "ภูเพียง",
          sub_district: "จอมจันทร์",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 6",
          province: "แพร่",
          district: "เมืองแพร่",
          sub_district: "สว่างอารมณ์",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },

        {
          idrole: "10666",
          namerole: "โรงพยาบาลมหาราชนครราชสีมา",
          area: "เขต 1",
          province: "นครราชสีมา",
          district: "หนองบัวลำภู",
          sub_district: "หนองบัวลำภู",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 2",
          province: "หนองบัวลำภู",
          district: "นาหนองหลวง",
          sub_district: "นาหนองหลวง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลมหาราชนครราชสีมา",
          area: "เขต 1",
          province: "บุรีรัมย์",
          district: "นางรอง",
          sub_district: "นางรอง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 3",
          province: "สระแก้ว",
          district: "มวกเหล็ก",
          sub_district: "มวกเหล็ก",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 3",
          province: "ชัยภูมิ",
          district: "หนองบัวแดง",
          sub_district: "หนองบัวแดง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 2",
          province: "อุดรธาณี",
          district: "กุดจอก",
          sub_district: "กุดจอก",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 4",
          province: "เชียงใหม่",
          district: "สันป่าตอง",
          sub_district: "สันป่าตอง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 4",
          province: "แม่ฮ่องสอน",
          district: "ปาย",
          sub_district: "ปาย",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 5",
          province: "ลำพูน",
          district: "ป่าซาง",
          sub_district: "ป่าซาง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 5",
          province: "ลำปาง",
          district: "แม่เมาะ",
          sub_district: "แม่เมาะ",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 6",
          province: "น่าน",
          district: "แม่จริม",
          sub_district: "แม่จริม",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 6",
          province: "แพร่",
          district: "ร้องกวาง",
          sub_district: "ร้องกวาง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },

        {
          idrole: "10666",
          namerole: "โรงพยาบาลมหาราชนครราชสีมา",
          area: "เขต 1",
          province: "นครราชสีมา",
          district: "หนองบัวลำภู",
          sub_district: "โคกสูง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 2",
          province: "หนองบัวลำภู",
          district: "นาหนองหลวง",
          sub_district: "โนนทอง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลมหาราชนครราชสีมา",
          area: "เขต 1",
          province: "บุรีรัมย์",
          district: "นางรอง",
          sub_district: "โนนดินแดง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 3",
          province: "สระแก้ว",
          district: "มวกเหล็ก",
          sub_district: "บ้านโสก",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 3",
          province: "ชัยภูมิ",
          district: "หนองบัวแดง",
          sub_district: "หนองนาคำ",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 2",
          province: "อุดรธาณี",
          district: "กุดจอก",
          sub_district: "บ้านแปร",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 4",
          province: "เชียงใหม่",
          district: "สันป่าตอง",
          sub_district: "หางดง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 4",
          province: "แม่ฮ่องสอน",
          district: "ปาย",
          sub_district: "แม่อาย",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 5",
          province: "ลำพูน",
          district: "ป่าซาง",
          sub_district: "ป่าโป่ง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 5",
          province: "ลำปาง",
          district: "แม่เมาะ",
          sub_district: "ทุ่งหลวง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 6",
          province: "น่าน",
          district: "แม่จริม",
          sub_district: "หนองแดง",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
        {
          idrole: "10666",
          namerole: "โรงพยาบาลหนองบัวลำภู",
          area: "เขต 6",
          province: "แพร่",
          district: "ร้องกวาง",
          sub_district: "นาทราย",
          type_hospital: "รพ.ศูนย์",
          list_all: "5,121 ",
          list_com: "500",
          list_wait: "4,621",
          right_hospital: "สิทธิ์บัตรทอง",
          type_logis: "rider",
        },
      ],
    };
  },
  computed: {
    filteredData() {
      if (!this.search) {
        return this.data_area;
      }
      const searchTerm = this.search.toLowerCase();
      return this.data_area.filter((item) =>
        Object.values(item).some(
          (val) =>
            typeof val === "string" && val.toLowerCase().includes(searchTerm)
        )
      );
    },
  },
};
</script>

<style></style>
